// Scaffolding and shell completions (catalogue 31, 33). Never calls a model.
import { cpSync, existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { Config } from "./config.js";
import { UsageError } from "./errors.js";

export interface InitReport {
  dest: string;
  written: string[];
  skipped: string[];
  text: string;
}

/**
 * Copy the shipped `config/` and `prompts/` into a new directory (catalogue 31).
 *
 * The point is not saving typing. `config/` is the product, and the shipped library is the only
 * thing in the repository with seven runs of evidence behind it — so a team extending it should
 * start from that and edit, rather than from a blank file and a schema. Every frame arrives with
 * its stance, probes and forbidden list intact, and the D6 orthogonality check is meaningful
 * from the first edit because there is something to be orthogonal to.
 *
 * Never overwrites. A `config/` that already exists is somebody's work.
 */
export function initConfig(cfg: Config, dest: string, opts: { force?: boolean } = {}): InitReport {
  const written: string[] = [];
  const skipped: string[] = [];
  mkdirSync(dest, { recursive: true });
  // docs/TRAPS.md is not documentation from the loader's point of view: the critic brief renders
  // its detector lines verbatim, and `loadConfig` refuses a root without it. An earlier version
  // copied config/ and prompts/ only and produced a directory that would not load — caught by
  // the test that calls loadConfig on the copy rather than trusting the file list.
  for (const dir of ["config", "prompts", "docs"]) {
    const from = join(cfg.root, dir);
    const to = join(dest, dir);
    if (!existsSync(from)) continue;
    mkdirSync(to, { recursive: true });
    // Only what the loader needs from docs/; the rest is prose about this repository, not part
    // of a library somebody is extending.
    const wanted = dir === "docs" ? ["TRAPS.md"] : readdirSync(from);
    for (const f of wanted) {
      const target = join(to, f);
      if (existsSync(target) && !opts.force) {
        skipped.push(join(dir, f));
        continue;
      }
      cpSync(join(from, f), target, { recursive: true });
      written.push(join(dir, f));
    }
  }

  const lines = [`adhd init -> ${dest}`, ""];
  for (const w of written) lines.push(`  wrote   ${w}`);
  for (const s of skipped) lines.push(`  kept    ${s} (already there; --force to replace)`);
  lines.push("");
  if (written.length)
    lines.push(
      "The shipped library is the only thing here with recorded runs behind it, so edit it rather than starting from a blank file. Adding a frame needs D6's orthogonality check first: `adhd frames --orthogonality`.",
      `Point commands at this directory with --root ${dest}, and check it with \`adhd validate --root ${dest}\` and \`adhd doctor --root ${dest}\`.`,
    );
  else lines.push("Nothing written: every file was already there.");
  return { dest, written, skipped, text: lines.join("\n") };
}

/**
 * A completion script (catalogue 33), generated from the command tree rather than hand-written.
 *
 * Hand-written completions go stale the first time a flag is added and nobody notices, because
 * nothing tests them. Generating from the real command list means the worst case is a completion
 * that offers a verb which exists.
 */
export function completions(shell: string, verbs: string[], osVerbs: string[]): string {
  const all = verbs.join(" ");
  const os = osVerbs.join(" ");
  if (shell === "bash")
    return `# adhd bash completion. Generated by \`adhd completions bash\`; regenerate after a version bump.
_adhd() {
  local cur prev
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"
  if [ "\${COMP_WORDS[1]}" = "os" ] && [ "$COMP_CWORD" -eq 2 ]; then
    COMPREPLY=( $(compgen -W "${os}" -- "$cur") )
    return
  fi
  if [ "$COMP_CWORD" -eq 1 ]; then
    COMPREPLY=( $(compgen -W "${all}" -- "$cur") )
    return
  fi
  case "$prev" in
    --root|--recorded|--fixtures|--os-root|--out) COMPREPLY=( $(compgen -d -- "$cur") ) ;;
    --problem|--file) COMPREPLY=( $(compgen -f -- "$cur") ) ;;
    *) COMPREPLY=( $(compgen -f -- "$cur") ) ;;
  esac
}
complete -F _adhd adhd
`;
  if (shell === "zsh")
    return `#compdef adhd
# adhd zsh completion. Generated by \`adhd completions zsh\`; regenerate after a version bump.
_adhd() {
  local -a verbs os_verbs
  verbs=(${verbs.map((v) => `'${v}'`).join(" ")})
  os_verbs=(${osVerbs.map((v) => `'${v}'`).join(" ")})
  if (( CURRENT == 2 )); then
    _describe 'adhd command' verbs
    return
  fi
  if [[ "\${words[2]}" == "os" && CURRENT -eq 3 ]]; then
    _describe 'adhd os command' os_verbs
    return
  fi
  case "\${words[CURRENT-1]}" in
    --root|--recorded|--fixtures|--os-root|--out) _files -/ ;;
    *) _files ;;
  esac
}
_adhd "$@"
`;
  throw new UsageError(`unknown shell ${shell}. Known: bash, zsh`);
}

/**
 * What a clean checkout can actually demonstrate without a model (catalogue 60).
 *
 * The honest demo is not a run: D2 says this package never calls a model, so a run needs a host
 * to spawn subagents and there is none in `npm run demo`. What it can show end to end is
 * everything either side of that: the compile and the D5 preview a user would be asked to
 * confirm, and then a real recorded run's synthesis with its pruned block, plus the checks.
 *
 * Saying so is part of the demo. A demo that implied it had just reasoned would misrepresent the
 * one design decision the whole repository is built on.
 */
export function demoScript(): string {
  return `#!/usr/bin/env bash
# What a clean checkout can show without a model. Generated intent, hand-maintained script.
#
# This package never calls a model (D2 in docs/DECISIONS.md), so a demo cannot produce a run:
# a run needs a host to spawn isolated subagents. What it shows is everything either side of
# that boundary, which is the part this repository actually is.
set -euo pipefail
cd "$(dirname "$0")/.."

step() { printf '\\n\\033[1m== %s\\033[0m\\n\\n' "$1"; }

step "1. Build and check the library"
npm run build --silent
node dist/src/cli.js validate
node dist/src/cli.js doctor | tail -3

step "2. The frame library"
node dist/src/cli.js frames | tail -5

step "3. Compile a problem and show the D5 gate"
printf 'What timeouts should I set on this HTTP client?' > /tmp/adhd-demo-problem.txt
node dist/src/cli.js run --phase compile \\
  --problem /tmp/adhd-demo-problem.txt \\
  --decision '{"problem_class":"design_decision"}' \\
  --runs-dir /tmp/adhd-demo-runs | head -30

echo
echo "Nothing has been spent. A host would now spawn one subagent per brief; this package"
echo "never does that itself, which is the whole of D2."

step "4. A run that did happen, with its pruned block"
node dist/src/cli.js why evals/recorded/001-first-run FRAME_BREAKER | head -25

step "5. What the corpus says about the library"
node dist/src/cli.js frames --health | tail -6
node dist/src/cli.js cost | tail -3

step "6. The harness"
node dist/src/cli.js eval | tail -3
node dist/src/cli.js matrix | tail -4

printf '\\nEverything above ran from the recorded corpus and the compiler. No model was called.\\n'
`;
}

/** Write the demo script, used by the test that keeps it in step with the CLI. */
export function writeDemo(root: string): string {
  const p = join(root, "scripts", "demo.sh");
  mkdirSync(join(root, "scripts"), { recursive: true });
  writeFileSync(p, demoScript(), { mode: 0o755 });
  return p;
}

/** Verbs the demo script invokes, for a test that no longer-existing verb is named. */
export function verbsUsedByDemo(root: string): string[] {
  const p = join(root, "scripts", "demo.sh");
  if (!existsSync(p)) return [];
  const text = readFileSync(p, "utf8");
  const out = new Set<string>();
  for (const m of text.matchAll(/cli\.js\s+([a-z-]+)/g)) out.add(m[1]!);
  return [...out].sort();
}
